spring:
  session:
    timeout:
       seconds: 900
    store-type: jdbc # Session store type. none, desactiva spring-session
    jdbc:      
      cleanup-cron: 0 * * * * * #Formato
      initialize-schema: always # Database schema initialization mode.
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql # Path to the SQL file to use to initialize the database schema.
      table-name: SPRING_SESSION 
  banner:
    charset: UTF-8
    location: classpath:/banners/banner.txt
  datasource:
    url: jdbc:mysql://tlaloc-son.com:3310/prueba?useSSL=false&noAccessToProcedureBodies=true
    username: personal
    password: QwrAsf124
  thymeleaf:
    cache: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/views/ 
    suffix: .html
  security:    
    filter: 
      order: -100
server:
  servlet:
      context-path: /personal
  port: 8087  
  error:
    whitelabel:
      enabled: true
    path: /error